openapi: '3.0.2'
info:
  title: Quote API
  version: '1.0'
servers:
  - url: https://api.predic8.de/v1
paths:
  /quotes:
    post:
      operationId: createQuote
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - product
              properties:
                id:
                  type: string
                  format: uuid
                  maxLength: 36
                product:
                  type: string
      responses:
        '200':
          description: OK