openapi: '3.0.2'
info:
  title: Quote API
  version: '1.0'
servers:
  - url: https://api.predic8.de/v1
paths:
  /quotes:
    post:
      operationId: createQuote
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 0
                  maximum: 10000
                product:
                  type: string
                  maxLength: 100
                  pattern: ".*"
                shipment:
                  type: string
                  enum:
                    - DOT
                    - FOB
      responses:
        '200':
          description: OK