name: Syntax

on:
  - pull_request

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral -r .syntax-spectral.yml lint quote-api-v1.yml
